version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      angular-and-typescript:
        dependencies:
          - "@angular/core"
          - "@angular/cli"
          - "@angular/common"
          - "@angular/compiler"
          - "@angular/compiler-cli"
          - "@angular/forms"
          - "@angular/platform-browser"
          - "@angular/platform-browser-dynamic"
          - "@angular/router"
          - "typescript"
    ignore:
      - dependency-name: "typescript"
        versions:
          - ">5.6.3"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
