version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      angular-typescript-group:
        patterns:
          - "^@angular/"
          - "^typescript$"
    labels:
      - "angular-typescript-updates"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      other-dependencies:
        patterns:
          - "*"
    labels:
      - "other-dependencies-updates"
    ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "typescript"
